backend:
  name: github
  repo: leo-le-07/gatsby-landing-page

media_folder: static/assets
public_folder: assets

collections:
  - name: news
    label: News
    folder: news
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: "Publish Date", widget: date }
      - { name: thumbnail, label: "Featured Image", widget: image}
      - { name: title, label: Title, widget: string }
      - { name: body, label: News, widget: markdown }